// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | ButtonSlice
  | TopicsSlice
  | TextCardSlice
  | CarouselCardSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Company Name field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Header Title field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header_title: prismic.RichTextField;

  /**
   * Header Image 1 field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image_1: prismic.ImageField<never>;

  /**
   * Header Image 2 field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.header_image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image_2: prismic.ImageField<never>;

  /**
   * About Paragrath 1 field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_paragrath_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_paragrath_1: prismic.RichTextField;

  /**
   * About Paragrath 2 field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_paragrath_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_paragrath_2: prismic.RichTextField;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *Button → Primary*
 */
export interface ButtonSliceDefaultPrimary {
  /**
   * Text field in *Button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: button.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *Button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: button.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Button Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Button*
 */
type ButtonSliceVariation = ButtonSliceDefault;

/**
 * Button Shared Slice
 *
 * - **API ID**: `button`
 * - **Description**: Button
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ButtonSlice = prismic.SharedSlice<"button", ButtonSliceVariation>;

/**
 * Primary content in *CarouselCard → Items*
 */
export interface CarouselCardSliceDefaultItem {
  /**
   * Image field in *CarouselCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_card.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CarouselCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_card.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *CarouselCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_card.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for CarouselCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CarouselCardSliceDefaultItem>
>;

/**
 * Slice variation for *CarouselCard*
 */
type CarouselCardSliceVariation = CarouselCardSliceDefault;

/**
 * CarouselCard Shared Slice
 *
 * - **API ID**: `carousel_card`
 * - **Description**: CarouselCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselCardSlice = prismic.SharedSlice<
  "carousel_card",
  CarouselCardSliceVariation
>;

/**
 * Primary content in *Map → Items*
 */
export interface MapSliceDefaultItem {
  /**
   * image field in *Map → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: map.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Map Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MapSliceDefaultItem>
>;

/**
 * Slice variation for *Map*
 */
type MapSliceVariation = MapSliceDefault;

/**
 * Map Shared Slice
 *
 * - **API ID**: `map`
 * - **Description**: Map
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSlice = prismic.SharedSlice<"map", MapSliceVariation>;

/**
 * Primary content in *TextCard → Items*
 */
export interface TextCardSliceDefaultItem {
  /**
   * Title field in *TextCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_card.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *TextCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_card.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for TextCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TextCardSliceDefaultItem>
>;

/**
 * Slice variation for *TextCard*
 */
type TextCardSliceVariation = TextCardSliceDefault;

/**
 * TextCard Shared Slice
 *
 * - **API ID**: `text_card`
 * - **Description**: TextCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextCardSlice = prismic.SharedSlice<
  "text_card",
  TextCardSliceVariation
>;

/**
 * Primary content in *Topics → Items*
 */
export interface TopicsSliceDefaultItem {
  /**
   * text field in *Topics → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: topics.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Topics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopicsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TopicsSliceDefaultItem>
>;

/**
 * Slice variation for *Topics*
 */
type TopicsSliceVariation = TopicsSliceDefault;

/**
 * Topics Shared Slice
 *
 * - **API ID**: `topics`
 * - **Description**: Topics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopicsSlice = prismic.SharedSlice<"topics", TopicsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      ButtonSlice,
      ButtonSliceDefaultPrimary,
      ButtonSliceVariation,
      ButtonSliceDefault,
      CarouselCardSlice,
      CarouselCardSliceDefaultItem,
      CarouselCardSliceVariation,
      CarouselCardSliceDefault,
      MapSlice,
      MapSliceDefaultItem,
      MapSliceVariation,
      MapSliceDefault,
      TextCardSlice,
      TextCardSliceDefaultItem,
      TextCardSliceVariation,
      TextCardSliceDefault,
      TopicsSlice,
      TopicsSliceDefaultItem,
      TopicsSliceVariation,
      TopicsSliceDefault,
    };
  }
}
