// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = CardTestimonialSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * text_1 field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.text_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_1: prismic.RichTextField;

  /**
   * image_1 field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * textcontact field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.textcontact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textcontact: prismic.KeyTextField;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *CardTestimonial → Items*
 */
export interface CardTestimonialSliceDefaultItem {
  /**
   * TestimonialImage field in *CardTestimonial → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_testimonial.items[].testimonialimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testimonialimage: prismic.ImageField<never>;

  /**
   * TestimonialText field in *CardTestimonial → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_testimonial.items[].testiomonialtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testiomonialtext: prismic.RichTextField;

  /**
   * TestimonialName field in *CardTestimonial → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_testimonial.items[].testimonialname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonialname: prismic.RichTextField;

  /**
   * TestimonialScore field in *CardTestimonial → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: card_testimonial.items[].starscore
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  starscore: prismic.NumberField;
}

/**
 * Default variation for CardTestimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardTestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CardTestimonialSliceDefaultItem>
>;

/**
 * Slice variation for *CardTestimonial*
 */
type CardTestimonialSliceVariation = CardTestimonialSliceDefault;

/**
 * CardTestimonial Shared Slice
 *
 * - **API ID**: `card_testimonial`
 * - **Description**: CardTestimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardTestimonialSlice = prismic.SharedSlice<
  "card_testimonial",
  CardTestimonialSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      CardTestimonialSlice,
      CardTestimonialSliceDefaultItem,
      CardTestimonialSliceVariation,
      CardTestimonialSliceDefault,
    };
  }
}
