// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  button: dynamic(() => import("./Button")),
  carousel_card: dynamic(() => import("./CarouselCard")),
  map: dynamic(() => import("./Map")),
  text_card: dynamic(() => import("./TextCard")),
  topics: dynamic(() => import("./Topics")),
};
